default: &default
  adapter: postgresql
  host: 127.0.0.1
  pool: 5
  timeout: 5000
development:
  adapter: postgresql
  database: prelaunchr_development
  host: localhost
test:
  adapter: postgresql
  database: prelaunchr_test
  host: localhost
production:
  <<: *default
  database: prelaunchr
  username: rails
  password: <%= ENV['APP_DATABASE_PASSWORD'] %>